services:
  postgres:
    container_name: postgres_container
    image: postgres:17-alpine

    #    ports:
    #      - "5433:5432"
    #    # local postgres always running so changing this!


    healthcheck:
      # healthcheck runs a command repeatedly inside the container to check if it's actually ready
      # without this, 'depends_on' only waits for the container to start, not for postgres to be ready
      # pg_isready is a built-in postgres utility that pings postgres and returns success when ready
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s # run the check every 10 seconds
      timeout: 5s   # wait max 5 seconds for a response before marking as failed
      retries: 5    # mark as unhealthy after 5 consecutive failures

    environment:
      POSTGRES_USER: ${database_username}
      POSTGRES_PASSWORD: ${database_password}
      POSTGRES_DB: stoxy

    networks:
      - stoxy-network

  redis:
    container_name: redis_container
    image: redis:7-alpine

    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

    networks:
      - stoxy-network

  stoxy-app:
    container_name: stoxy-finance_container
    image: anshxcookies/stoxy-finance:latest
    # here . tells to build the image from the relative path dockerfile,
    # otherwise we would have to create always when the dockerfile
    # changes and give the path.
    # Moreover, postgres works by pulling the image from the DockerHub
    # which is not true in our case as we are not uploading to DockerHub!

    #    build: .  ## we don't need to build the image as we are pulling it from DockerHub, so commenting this out

    depends_on:
      postgres:
        condition: service_healthy

      redis:
        condition: service_healthy
    # depends_on with service_healthy waits until postgres health_check passes before starting stoxy-app
    # previously without condition, it only waited for the container to start, not for postgres to be ready

    #  depends_on:
    #   - postgres:
    # this field tells that this service depends on another service, so first
    # the depends on services are started completed and then this service runs!

    ports:
      - "8080:8080"
    # format is "hostPort:containerPort"
    # whenever something hits your machine on port 8080 (browser, postman)
    # docker intercepts and forwards it into the container at port 8080
    # without this, container runs but nothing outside can reach it
    # container-to-container communication doesn't need this, they talk via service names internally


    env_file: .env # get the values from the .env file
    environment:
      database_url: jdbc:postgresql://postgres:5432/stoxy # overriding!
      redis_host: redis
      # this means connect to the url by the postgres service

    networks:
      - stoxy-network
    # this explicitly tells this service to be on this method!

networks:
  stoxy-network:
    driver: bridge


# sudo docker compose up --build = --build forces docker-compose to rebuild the image every time instead of using cache.