import { lazy, Suspense, useEffect, useState } from 'react'
import { AnimatePresence, motion } from 'framer-motion'
import { ArrowRight, BookmarkPlus, Check, Command, Search, Sparkles, TrendingUp } from 'lucide-react'
import { Button } from './components/ui/button'
import { Card } from './components/ui/card'
import { Input } from './components/ui/input'
import { indexApi, stockApi, tickerApi, type IndexDetailResponseDTO, type IndexSearchDTO, type StockDetailResponseDTO, type StockSearchDTO } from './lib/api'

type Page = 'home' | 'stock' | 'index'
type SearchItem = StockSearchDTO | IndexSearchDTO
type Detail = { instrument: SearchItem; stock?: StockDetailResponseDTO; index?: IndexDetailResponseDTO; price?: number; previousClose?: number }
const MarketChart = lazy(() => import('./components/MarketChart').then(module => ({ default: module.MarketChart })))

function Marquee() {
  const [items, setItems] = useState<Array<{ name: string; price: number | null; change: number | null }>>([])
  useEffect(() => { let alive = true; void (async () => { try { const searches = await Promise.all(['NIFTY 50', 'NIFTY BANK', 'SENSEX'].map(indexApi.search)); const found = searches.flatMap(response => response.indexSearchDTOList).filter((item, index, all) => all.findIndex(candidate => candidate.instrumentKey === item.instrumentKey) === index); const quotes = await tickerApi.ltpc(found.map(item => item.instrumentKey)); if (alive) setItems(found.map(item => { const quote = quotes[item.instrumentKey]; return { name: item.indexName, price: quote?.ltp ?? null, change: quote?.ltp != null && quote.cp > 0 ? ((quote.ltp - quote.cp) / quote.cp) * 100 : null } })) } catch { /* non-blocking live marquee */ } })(); return () => { alive = false } }, [])
  const repeated = [...items, ...items, ...items, ...items]
  return <div className="marquee"><div className="marquee__track"><span className="marquee__label"><i/> LIVE MARKETS</span>{repeated.length ? repeated.map((item, index) => <b key={`${item.name}-${index}`}>{item.name} <em>{item.price == null ? '—' : item.price.toLocaleString('en-IN', { maximumFractionDigits: 2 })}</em><strong>{item.change == null ? '—' : `${item.change >= 0 ? '+' : ''}${item.change.toFixed(2)}%`}</strong></b>) : <b>CONNECTING LIVE MARKETS <em>—</em></b>}</div></div>
}
function Header({ page, setPage }: { page: Page; setPage: (page: Page) => void }) { return <header className="header shell"><button className="logo" onClick={() => setPage('home')}>Stoxy<b>.</b></button><nav>{(['home', 'stock', 'index'] as Page[]).map(item => <button key={item} className={page === item ? 'active' : ''} onClick={() => setPage(item)}>{item === 'home' ? 'Markets' : item === 'stock' ? 'Stocks' : 'Indices'}</button>)}</nav><div className="header__actions"><Button variant="ghost" size="sm" className="search-button" onClick={() => setPage('stock')}><Search size={15}/><span>Search the market</span><kbd><Command size={9}/> K</kbd></Button><Button size="sm" onClick={() => setPage('stock')}>Explore <ArrowRight size={14}/></Button></div></header> }
function Landing({ setPage }: { setPage: (page: Page) => void }) { return <><section className="hero shell"><div><p className="kicker"><i/> THE INDIAN MARKET, DECODED</p><h1>Find your next<br/><em>point of view.</em></h1><p className="hero__body">Search the market, explore the underlying data and only then ask for an extra layer of analysis.</p><div className="hero__actions"><Button variant="orange" onClick={() => setPage('stock')}>Search a stock <ArrowRight size={16}/></Button><Button variant="outline" onClick={() => setPage('index')}>Explore an index</Button></div></div><div className="pulse-window"><div className="pulse-window__top"><span><i/> LIVE DATA</span><small>STOXY MARKET EXPLORER</small></div><div className="pulse-window__copy"><p>START WITH THE</p><strong>Underlying data.</strong><span>Prices, fundamentals, index information and charts—before the narrative.</span></div></div></section><section className="section shell"><div className="section-title"><div><p className="kicker"><i/> FIND AN INSTRUMENT</p><h2>Search a stock or<br/>an <em>index.</em></h2></div><p>Every result opens a full, data-first detail view.</p></div><div className="principles"><article><span>01</span><h3>Search live instruments.</h3><p>Find the company or index through the existing backend directory.</p></article><article><span>02</span><h3>Study the facts.</h3><p>Read live price, fundamentals, metadata and chart history.</p></article><article><span>03</span><h3>Ask for analysis.</h3><p>Generate the optional AI briefing only when you are ready.</p></article></div></section></> }
function Explorer({ type }: { type: 'stock' | 'index' }) {
  const isStock = type === 'stock'
  const [query, setQuery] = useState('')
  const [matches, setMatches] = useState<SearchItem[]>([])
  const [detail, setDetail] = useState<Detail | null>(null)
  const [loading, setLoading] = useState(false)
  const [analysis, setAnalysis] = useState<string | null>(null)
  const [analysing, setAnalysing] = useState(false)
  const [error, setError] = useState('')
  const [saved, setSaved] = useState(false)
  useEffect(() => { let alive = true; const timer = window.setTimeout(() => { if (query.trim().length < 2) return setMatches([]); void (async () => { try { const response = isStock ? await stockApi.search(query) : await indexApi.search(query); if (alive) setMatches(isStock ? response.content : response.indexSearchDTOList) } catch { if (alive) setMatches([]) } })() }, 220); return () => { alive = false; window.clearTimeout(timer) } }, [query, isStock])
  const pick = async (instrument: SearchItem) => { setQuery(isStock ? (instrument as StockSearchDTO).stockName : (instrument as IndexSearchDTO).indexName); setMatches([]); setDetail(null); setAnalysis(null); setError(''); setLoading(true); try { const [quotes, record] = await Promise.all([tickerApi.ltpc([instrument.instrumentKey]), isStock ? stockApi.details(instrument as StockSearchDTO) : indexApi.details(instrument.instrumentKey)]); const quote = quotes[instrument.instrumentKey]; setDetail(isStock ? { instrument, stock: record as StockDetailResponseDTO, price: quote?.ltp, previousClose: quote?.cp } : { instrument, index: record as IndexDetailResponseDTO, price: quote?.ltp, previousClose: quote?.cp }) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not load instrument data.') } finally { setLoading(false) } }
  const generate = async () => { if (!detail) return; setAnalysing(true); setError(''); try { setAnalysis(isStock ? await stockApi.analyse(detail.instrument as StockSearchDTO) : await indexApi.analyse(detail.instrument as IndexSearchDTO)) } catch (cause) { setError(cause instanceof Error ? cause.message : 'Could not generate analysis.') } finally { setAnalysing(false) } }
  if (!detail) return <section className="analysis shell"><div className="breadcrumbs">Markets <span>/</span> {isStock ? 'Stocks' : 'Indices'}</div><div className="analysis__hero"><div><p className="kicker"><i/> {isStock ? 'STOCK EXPLORER' : 'INDEX EXPLORER'}</p><h1>Search. Study.<br/><em>Decide.</em></h1><p>Select an instrument from the real backend directory to view its data-first detail page.</p></div><div className="search-box"><label>SEARCH {isStock ? 'STOCKS' : 'INDICES'}<Input autoFocus value={query} placeholder={isStock ? 'Try HDFC Bank or TCS' : 'Try NIFTY 50'} onChange={event => setQuery(event.target.value)}/></label>{matches.length > 0 && <div className="search-results">{matches.map(item => <button key={item.instrumentKey} onClick={() => void pick(item)}><span>{isStock ? (item as StockSearchDTO).stockName : (item as IndexSearchDTO).indexName}</span><small>{isStock ? `${(item as StockSearchDTO).stockSymbol} · ${(item as StockSearchDTO).exchange}` : `${(item as IndexSearchDTO).indexSymbol} · ${(item as IndexSearchDTO).exchange}`}</small></button>)}</div>}<small>Choose a result to open its full detail view.</small></div></div>{loading && <div className="api-message">Loading live instrument data…</div>}{error && <div className="api-message api-message--error">{error}</div>}</section>
  const name = isStock ? detail.stock?.stockName : detail.index?.indexName
  const symbol = isStock ? detail.stock?.stockSymbol : detail.index?.indexSymbol
  const change = detail.price != null && detail.previousClose ? ((detail.price - detail.previousClose) / detail.previousClose) * 100 : null
  return <section className="analysis shell detail-page"><div className="breadcrumbs">Markets <span>/</span> {isStock ? 'Stocks' : 'Indices'} <span>/</span> {symbol}</div><button className="back-to-search" onClick={() => { setDetail(null); setQuery(''); setAnalysis(null) }}>← Search another {isStock ? 'stock' : 'index'}</button><header className="instrument"><div className="company"><div className={`company__mark ${!isStock ? 'company__mark--index' : ''}`}>{isStock ? name?.charAt(0) : '50'}</div><div><p className="micro">{detail.instrument.exchange} · {symbol}</p><h2>{name}</h2><span>{detail.stock?.companyResponseDTO?.sector ?? detail.index?.indexMetadataDTO?.methodology ?? '—'}</span></div></div><div className="quote"><span>LAST TRADED {isStock ? 'PRICE' : 'VALUE'}</span><strong>{detail.price == null ? '—' : detail.price.toLocaleString('en-IN', { style: isStock ? 'currency' : 'decimal', currency: 'INR', maximumFractionDigits: 2 })}</strong><b>{change == null ? 'Awaiting live quote' : `${change >= 0 ? '↑ +' : '↓ '}${change.toFixed(2)}% today`}</b></div><div className="detail-actions"><Button variant="outline" size="sm" onClick={() => setSaved(!saved)}>{saved ? <><Check size={14}/> Watching</> : <><BookmarkPlus size={14}/> Watchlist</>}</Button><Button variant="orange" size="sm" disabled={analysing} onClick={() => void generate()}>{analysing ? 'Analysing…' : 'AI analyse'} <Sparkles size={14}/></Button></div></header>{error && <div className="api-message api-message--error">{error}</div>}{analysis && <Card className="live-analysis live-analysis--top"><div className="card-heading"><div><p className="micro">AI RESEARCH BRIEFING · {symbol}</p><h3>Here’s what changed for <em>{name}.</em></h3></div><span>LIVE RESPONSE</span></div><AnalysisText text={analysis}/></Card>}<div className="analysis-grid"><main><Suspense fallback={<div className="chart-loading">Preparing chart…</div>}><MarketChart instrumentKey={detail.instrument.instrumentKey}/></Suspense>{isStock && detail.stock && <LiveFundamentals detail={detail.stock}/>}<Card className="detail-card"><p className="micro">ABOUT</p><p>{detail.stock?.companyResponseDTO?.description ?? detail.index?.indexMetadataDTO?.description ?? 'No description was returned for this instrument.'}</p></Card>{!isStock && detail.index && <IndexMetrics detail={detail.index}/>}</main><aside><InfoPanel stock={detail.stock} index={detail.index} instrument={detail.instrument}/></aside></div></section>
}
function AnalysisText({ text }: { text: string }) { return <div className="analysis-text">{text.split(/\n\s*\n/).filter(Boolean).map((chunk, index) => <p key={`${index}-${chunk.slice(0, 16)}`}>{chunk.replace(/^#{1,6}\s*/gm, '')}</p>)}</div> }
function LiveFundamentals({ detail }: { detail: StockDetailResponseDTO }) { const f = detail.stockFinancialsDTO; return <div className="factors">{[['P/E RATIO', f.pe == null ? '—' : `${f.pe.toFixed(2)}x`, `Sector ${f.sectorPe?.toFixed(2) ?? '—'}x`], ['PRICE / BOOK', f.pb == null ? '—' : `${f.pb.toFixed(2)}x`, `Sector ${f.sectorPb?.toFixed(2) ?? '—'}x`], ['RETURN ON EQUITY', f.roe == null ? '—' : `${f.roe.toFixed(2)}%`, `Sector ${f.sectorRoe?.toFixed(2) ?? '—'}%`]].map(([label, value, text]) => <div key={label}><span>{label}</span><strong>{value}</strong><p>{text}</p></div>)}</div> }
function IndexMetrics({ detail }: { detail: IndexDetailResponseDTO }) { const p = detail.indexPriceInfoDTO; const a = detail.indexAdvanceDTO; const items = [['DAY RANGE', p ? `${p.dayLow?.toLocaleString('en-IN') ?? '—'} — ${p.dayHigh?.toLocaleString('en-IN') ?? '—'}` : '—'], ['52 WEEK RANGE', p ? `${p.yearLow?.toLocaleString('en-IN') ?? '—'} — ${p.yearHigh?.toLocaleString('en-IN') ?? '—'}` : '—'], ['ADVANCES / DECLINES', a ? `${a.advances} / ${a.declines}` : '—'], ['CONSTITUENTS', detail.indexMetadataDTO?.numberOfConstituents?.toString() ?? '—']]; return <div className="index-metrics">{items.map(([label, value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div> }
function InfoPanel({ stock, index, instrument }: { stock?: StockDetailResponseDTO; index?: IndexDetailResponseDTO; instrument: SearchItem }) { const metadata = index?.indexMetadataDTO; const rows = stock ? [['Company', stock.companyResponseDTO?.companyName], ['Symbol', stock.stockSymbol], ['Exchange', stock.exchange], ['ISIN', stock.isin], ['Sector', stock.companyResponseDTO?.sector], ['Sector MCap', stock.companyResponseDTO?.sectorMarketCap]] : [['Symbol', index?.indexSymbol], ['Exchange', instrument.exchange], ['Constituents', metadata?.numberOfConstituents], ['Launch Date', metadata?.launchDate], ['Base Date', metadata?.baseDate], ['Methodology', metadata?.methodology], ['Status', metadata?.isActive ? 'Active' : 'Inactive']]; return <Card className="info-panel"><p className="micro">{stock ? 'STOCK INFO' : 'INDEX INFO'}</p>{rows.filter(([, value]) => value != null && value !== '').map(([label, value]) => <div key={label}><span>{label}</span><b>{String(value)}</b></div>)}</Card> }
function App() { const [page, setPage] = useState<Page>('home'); return <><Marquee/><Header page={page} setPage={setPage}/><AnimatePresence mode="wait">{page === 'home' ? <motion.div key="home" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><Landing setPage={setPage}/></motion.div> : <motion.div key={page} initial={{ opacity: 0, y: 14 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -14 }}><Explorer type={page}/></motion.div>}</AnimatePresence><footer className="footer shell"><button className="logo" onClick={() => setPage('home')}>Stoxy<b>.</b></button><span>A calmer way to understand the market.</span><span>© 2026</span></footer></> }
export default App
