import { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { getAnalysis } from './api';

const market = [
  ['NIFTY 50', '24,781.50', '+0.64%'], ['SENSEX', '81,385.43', '+0.52%'],
  ['NIFTY BANK', '55,626.10', '+0.79%'], ['RELIANCE', '1,431.20', '+1.26%'],
  ['TCS', '3,154.60', '+0.43%'], ['HDFCBANK', '1,971.80', '+0.85%']
];
const stocks = [
  { name: 'Reliance Industries', symbol: 'RELIANCE', price: '₹1,431.20', change: '+1.26%', tone: 'violet' },
  { name: 'HDFC Bank', symbol: 'HDFCBANK', price: '₹1,971.80', change: '+0.85%', tone: 'coral' },
  { name: 'Tata Consultancy Services', symbol: 'TCS', price: '₹3,154.60', change: '+0.43%', tone: 'blue' },
  { name: 'ICICI Bank', symbol: 'ICICIBANK', price: '₹1,412.50', change: '+1.63%', tone: 'mint' }
];

function Icon({ name, size = 18 }) {
  const paths = { arrow: 'M5 12h14m-6-6 6 6-6 6', spark: 'm12 3-1.7 5.3L5 10l5.3 1.7L12 17l1.7-5.3L19 10l-5.3-1.7L12 3Z', search: 'm21 21-4.3-4.3M19 11a8 8 0 1 1-16 0 8 8 0 0 1 16 0Z', grid: 'M4 4h6v6H4zM14 4h6v6h-6zM4 14h6v6H4zM14 14h6v6h-6z', plus: 'M12 5v14M5 12h14', bell: 'M18 8a6 6 0 0 0-12 0c0 7-3 7-3 9h18c0-2-3-2-3-9M10 21h4', chart: 'M4 19V5m0 14h16M7 15l3-3 3 2 5-6', wallet: 'M4 7h15a1 1 0 0 1 1 1v10a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V6a2 2 0 0 1 2-2h12', menu: 'M4 7h16M4 12h16M4 17h16', close: 'M6 6l12 12M18 6 6 18', chevron: 'm9 18 6-6-6-6' };
  return <svg width={size} height={size} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" strokeLinecap="round" strokeLinejoin="round"><path d={paths[name]} /></svg>;
}

function Ticker() { return <div className="ticker"><div className="ticker-track">{[...market, ...market].map(([name, value, change], index) => <div className="ticker-item" key={index}><span>{name}</span><b>{value}</b><em>{change}</em></div>)}</div></div> }
function Logo() { return <button className="logo" onClick={() => location.hash = ''}><i>✦</i> stoxy<span>.</span></button> }
function LineChart({ mini = false }) { return <svg className={mini ? 'mini-chart' : 'line-chart'} viewBox="0 0 480 170" preserveAspectRatio="none"><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#ff7a1a" stopOpacity=".28"/><stop offset="1" stopColor="#ff7a1a" stopOpacity="0"/></linearGradient></defs>{!mini && <><path className="grid" d="M0 35H480M0 85H480M0 135H480"/></>}<path className="area" d="M0 135 C23 137 35 109 58 119 S89 107 108 113 S145 87 165 103 S203 96 218 81 S251 88 270 67 S300 92 320 70 S348 77 369 50 S403 58 425 34 S461 42 480 13 V170H0Z"/><path className="stroke" d="M0 135 C23 137 35 109 58 119 S89 107 108 113 S145 87 165 103 S203 96 218 81 S251 88 270 67 S300 92 320 70 S348 77 369 50 S403 58 425 34 S461 42 480 13"/></svg> }
function StockLogo({ symbol, tone }) { return <div className={'stock-logo ' + tone}>{symbol.slice(0, 1)}</div> }
function StockRow({ stock, compact = false }) { return <div className={'stock-row ' + (compact ? 'compact' : '')}><StockLogo symbol={stock.symbol} tone={stock.tone}/><div className="stock-ident"><b>{stock.name}</b><span>{stock.symbol} · NSE</span></div>{!compact && <LineChart mini/>}<div className="stock-price"><b>{stock.price}</b><em>{stock.change}</em></div>{!compact && <button className="icon-button" aria-label="Add to watchlist"><Icon name="plus" /></button>}</div> }

function App() {
  const [page, setPage] = useState(location.hash.replace('#/', '') || 'home');
  const [menu, setMenu] = useState(false);
  useEffect(() => { const sync = () => setPage(location.hash.replace('#/', '') || 'home'); addEventListener('hashchange', sync); return () => removeEventListener('hashchange', sync); }, []);
  const go = (next) => { location.hash = next === 'home' ? '' : '/' + next; setMenu(false); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  if (page === 'login') return <Login go={go} />;
  if (page !== 'home') return <AppShell page={page} go={go} />;
  return <Landing go={go} menu={menu} setMenu={setMenu} />;
}

function Landing({ go, menu, setMenu }) { return <div className="landing"><header className="top-nav"><Logo/><nav className={menu ? 'open' : ''}><a href="#product">Product</a><a href="#intelligence">AI Intelligence</a><a href="#roadmap">Roadmap</a><a href="#about">About</a></nav><div className="nav-actions"><button className="text-button" onClick={() => go('login')}>Sign in</button><button className="button small" onClick={() => go('dashboard')}>Enter Stoxy <Icon name="arrow" size={15}/></button><button className="menu-button" onClick={() => setMenu(!menu)}><Icon name={menu ? 'close' : 'menu'}/></button></div></header><Ticker/>
  <main>
    <section className="hero"><div className="orb orb-one"/><div className="orb orb-two"/><div className="hero-copy"><p className="eyebrow"><Icon name="spark" size={14}/> The intelligent way to invest</p><h1>See the market<br/><i>before it moves.</i></h1><p className="hero-sub">Stoxy brings your market, research, and investing decisions into one calm, intelligent workspace built for Indian markets.</p><div className="hero-actions"><button className="button" onClick={() => go('dashboard')}>Explore the terminal <Icon name="arrow"/></button><button className="play-button"><span>▶</span> See how it works</button></div><div className="trust-row"><div className="avatars"><i>R</i><i>S</i><i>A</i></div><span>Built for thoughtful investors, not noisy feeds.</span></div></div><HeroPreview go={go}/></section>
    <section className="signal-strip"><p><span className="live-dot"/> MARKET SIGNAL</p><strong>India is pricing in a new growth cycle.</strong><span>Our AI is reading between the lines. <button onClick={() => go('dashboard')}>Explore today’s signal <Icon name="arrow" size={14}/></button></span></section>
    <section id="intelligence" className="terminal-promise"><div><p className="eyebrow"><Icon name="spark" size={14}/> Intelligence, in context</p><h2>Research belongs<br/><i>beside the tape.</i></h2><p>Stoxy AI lives on the securities and indices you are actively evaluating — not in a generic dashboard feed.</p></div><div className="terminal-promise-card"><div className="tape-header"><span>RELIANCE · NSE</span><b>₹1,431.20 <em>+1.26%</em></b></div><div className="tape-grid"><div><small>OPEN</small><b>1,414.90</b></div><div><small>DAY HIGH</small><b>1,437.75</b></div><div><small>DAY LOW</small><b>1,406.25</b></div></div><div className="ai-action-preview"><span>✦</span><div><b>Ask Stoxy AI</b><small>Thesis, risk and key signals — on demand</small></div><Icon name="arrow" size={16}/></div></div></section>
    <section className="showcase"><div className="showcase-copy"><p className="eyebrow">One considered workspace</p><h2>Every signal.<br/>One <i>view.</i></h2><p>From the opening bell to your next big idea, your complete market context is never more than a glance away.</p><button className="inline-link" onClick={() => go('dashboard')}>Explore the dashboard <Icon name="arrow" size={15}/></button></div><DashboardShot/></section>
    <section id="about" className="closing"><div className="closing-glow"/><p className="eyebrow">Your next decision starts here</p><h2>Invest with more<br/><i>intention.</i></h2><button className="button" onClick={() => go('dashboard')}>Start exploring Stoxy <Icon name="arrow"/></button></section>
  </main><Footer/></div> }
function HeroPreview({ go }) { return <motion.div className="hero-preview" initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: .8, delay: .15, ease: 'easeOut' }}><div className="preview-top"><span className="preview-logo">✦ STOXY</span><span className="preview-search"><Icon name="search" size={14}/> Search markets</span><span className="preview-avatar">A</span></div><div className="preview-body"><aside><i className="active"><Icon name="grid" size={16}/></i><i><Icon name="chart" size={16}/></i><i><Icon name="wallet" size={16}/></i></aside><div className="preview-main"><div className="preview-label"><span>MARKET OVERVIEW</span><b>Good morning, Ansh <em>↗</em></b></div><div className="preview-index"><div><span>NIFTY 50</span><strong>24,781.50</strong><em>+156.20 (0.64%)</em></div><LineChart/><div className="range"><span>1D</span><span>1W</span><span className="selected">1M</span><span>1Y</span></div></div></div><div className="preview-side"><span>WATCHLIST</span>{stocks.slice(0,3).map(stock => <div className="tiny-stock" key={stock.symbol}><StockLogo symbol={stock.symbol} tone={stock.tone}/><b>{stock.symbol}</b><em>{stock.change}</em></div>)}<button onClick={() => go('dashboard')}>Open terminal <Icon name="arrow" size={13}/></button></div></div></motion.div> }
function Feature({ number, icon, title, text }) { return <article className="feature"><div className="feature-top"><span>{number}</span><i><Icon name={icon}/></i></div><h3>{title}</h3><p>{text}</p><a href="#intelligence">Explore <Icon name="arrow" size={14}/></a></article> }
function DashboardShot() { return <div className="dashboard-shot"><div className="shot-header"><b>Market overview</b><span>Today, Aug 01 <Icon name="chevron" size={13}/></span></div><div className="shot-stats"><div><small>YOUR PORTFOLIO</small><strong>₹12,48,790</strong><em>+₹14,230 · 1.15% today</em></div><div className="shot-donut">68<small>Health score</small></div></div><div className="shot-chart"><small>PORTFOLIO PERFORMANCE</small><LineChart/></div></div> }
function Roadmap({ phase, title, text, active }) { return <div className={'roadmap-card ' + (active ? 'active' : '')}><span>{phase}</span><div className="roadmap-point"/><h3>{title}</h3><p>{text}</p>{!active && <small>COMING SOON</small>}</div> }

function AppShell({ page, go }) { const [searchOpen, setSearchOpen] = useState(false); const nav = [['dashboard','Overview','grid'],['watchlist','Watchlist','chart'],['portfolio','Portfolio','wallet'],['screener','Screener','search']]; const titles = { dashboard: ['Market overview.', 'Live indices, market breadth and active opportunities.'], watchlist: ['Your watchlist.', 'A focused view of companies worth watching.'], portfolio: ['Your portfolio.', 'A clearer picture of your investing journey.'], screener: ['Discover opportunities.', 'Filter the market by the signals that matter.'], stock: ['Reliance Industries', 'RELIANCE · NSE'], index: ['NIFTY 50', 'NSE INDEX · Live market detail'] };
return <div className="app-shell"><aside className="side-nav"><Logo/><div className="side-links">{nav.map(([id,label,icon])=><button className={page===id?'active':''} onClick={()=>go(id)} key={id}><Icon name={icon}/><span>{label}</span></button>)}</div><div className="side-bottom"><button onClick={()=>go('stock')}><Icon name="spark"/><span>Stoxy AI</span><em>DETAIL VIEW</em></button><button><span className="user-dot">A</span><span>Ans</span><Icon name="chevron" size={13}/></button></div></aside><div className="mobile-header"><Logo/><button onClick={()=>setSearchOpen(true)}><Icon name="search"/></button><button><Icon name="bell"/></button></div><main className="workspace"><Ticker/><header className="workspace-header"><div><p className="eyebrow">{page === 'dashboard' ? 'MARKET DESK · FRIDAY, 01 AUGUST' : 'STOXY / ' + page.toUpperCase()}</p><h1>{titles[page]?.[0]} <span>{page === 'dashboard' && '↗'}</span></h1><p>{titles[page]?.[1]}</p></div><div className="workspace-actions"><button className="search-trigger" onClick={()=>setSearchOpen(true)}><Icon name="search" size={16}/> Search stocks <kbd>⌘ K</kbd></button><button className="icon-button"><Icon name="bell"/></button><button className="button small">+ Add investment</button></div></header>{page==='dashboard' && <Dashboard go={go}/>} {page==='watchlist' && <Watchlist go={go}/>} {page==='portfolio' && <Portfolio/>} {page==='screener' && <Screener go={go}/>} {page==='stock' && <StockDetail/>} {page==='index' && <IndexDetail/>}</main>{searchOpen && <SearchModal close={()=>setSearchOpen(false)} go={go}/>}</div> }
function Dashboard({ go }) { return <div className="dashboard-content"><section className="market-overview"><div className="section-title"><div><small><span className="live-dot"/> LIVE MARKET</small><h2>The Indian market, at a glance.</h2></div><button className="outline-button" onClick={()=>go('index')}>Open index desk <Icon name="arrow" size={15}/></button></div><div className="market-deck">{[['NIFTY 50','24,781.50','+0.64%'],['SENSEX','81,385.43','+0.52%'],['NIFTY BANK','55,626.10','+0.79%']].map(([name,price,move])=><button onClick={()=>go('index')} className="market-quote" key={name}><span>{name}</span><b>{price}</b><em>↑ {move}</em><LineChart mini/><i>↗</i></button>)}</div><div className="index-card terminal-chart"><div className="index-copy"><span>NIFTY 50 · NSE INDEX</span><h2>24,781.50</h2><em>↑ 156.20 <b>(0.64%)</b> Today</em><div className="terminal-stats"><span>OPEN <b>24,669.30</b></span><span>HIGH <b>24,812.65</b></span></div><div className="range-tabs"><button className="selected">1D</button><button>1W</button><button>1M</button><button>1Y</button><button>MAX</button></div></div><div className="main-chart"><LineChart/><span className="chart-label label-a">24,860.12</span><span className="chart-label label-b">24,625.40</span></div></div></section><section className="dash-grid"><div className="holdings-panel panel"><div className="panel-heading"><div><small>YOUR HOLDINGS</small><h3>Steady progress.</h3></div><button onClick={()=>go('portfolio')}>View portfolio <Icon name="arrow" size={14}/></button></div><div className="portfolio-number"><strong>₹12,48,790</strong><em>+₹14,230 <b>+1.15%</b> today</em></div><LineChart mini/><div className="holding-summary"><span>Invested <b>₹10,92,400</b></span><span>All-time returns <b>+14.31%</b></span></div></div><div className="watch-panel panel"><div className="panel-heading"><div><small>ACTIVE WATCHLIST</small><h3>Trade ideas.</h3></div><button onClick={()=>go('watchlist')}>See all <Icon name="arrow" size={14}/></button></div>{stocks.slice(0,3).map(stock=><StockRow stock={stock} compact key={stock.symbol}/>)}</div></section><section className="trade-tape"><div><small>MARKET BREADTH</small><strong>34 <em>ADVANCING</em></strong><span>16 declining · 4 unchanged</span></div><div className="breadth-bar"><i/><b/></div><div><small>MOST ACTIVE</small><strong>RELIANCE <em>+1.26%</em></strong><button onClick={()=>go('stock')}>Open chart <Icon name="arrow" size={13}/></button></div></section></div> }
function Watchlist({ go }) { return <div className="list-page"><div className="list-toolbar"><div className="tabs"><button className="active">Core watchlist <b>12</b></button><button>Recent</button></div><button className="button small" onClick={()=>go('screener')}><Icon name="plus" size={15}/> Discover stocks</button></div><div className="table-head"><span>COMPANY</span><span>PRICE</span><span>1D CHANGE</span><span>30D PERFORMANCE</span><span/></div><div className="stock-list">{stocks.map(stock=><StockRow stock={stock} key={stock.symbol}/>)}</div><div className="watch-note"><Icon name="spark"/><span><b>Watchlists are better with a point of view.</b> Stoxy AI research is coming soon.</span></div></div> }
function Portfolio() { return <div className="portfolio-page"><div className="portfolio-hero"><div><small>ESTIMATED VALUE</small><h2>₹12,48,790</h2><em>↑ ₹1,56,390 <b>+14.31%</b> all time</em></div><div className="portfolio-summary"><span><small>INVESTED</small><b>₹10,92,400</b></span><span><small>DAY'S RETURN</small><b className="positive">+₹14,230</b></span><span><small>HOLDINGS</small><b>08</b></span></div></div><div className="allocation-grid"><div className="panel allocation"><div className="panel-heading"><div><small>ALLOCATION</small><h3>Where your capital sits.</h3></div></div><div className="allocation-body"><div className="donut"><div>8<small>holdings</small></div></div><div className="legend"><span><i className="lg-orange"/> Financials <b>32.4%</b></span><span><i className="lg-violet"/> Technology <b>24.8%</b></span><span><i className="lg-blue"/> Energy <b>18.2%</b></span><span><i className="lg-gray"/> Other <b>24.6%</b></span></div></div></div><div className="panel portfolio-empty"><div className="empty-mark"><Icon name="spark"/></div><small>PORTFOLIO INTELLIGENCE</small><h3>A more thoughtful review is on its way.</h3><p>Stoxy will soon help you understand allocation, concentration and risk at a glance.</p><span>COMING SOON</span></div></div></div> }
function Screener({ go }) { const [filter, setFilter] = useState('All stocks'); return <div className="screener-page"><div className="preset-row">{['All stocks','High growth','Strong momentum','Value picks','Large cap'].map(item=><button className={filter===item?'active':''} onClick={()=>setFilter(item)} key={item}>{item}</button>)}</div><div className="screener-layout"><aside className="filter-panel"><div><small>FILTERS</small><button>Reset all</button></div>{['Market cap','Sector','Price range','Performance','Fundamentals'].map(filterName=><button className="filter-row" key={filterName}>{filterName}<Icon name="chevron" size={14}/></button>)}</aside><div className="results"><div className="results-head"><b>1,924 companies</b><span>Sorted by <button>Market cap <Icon name="chevron" size={12}/></button></span></div><div className="table-head"><span>COMPANY</span><span>PRICE</span><span>1D CHANGE</span><span>30D PERFORMANCE</span><span/></div>{stocks.concat(stocks.slice(0,2)).map((stock,index)=><div onClick={()=>go('stock')} className="click-row" key={stock.symbol+index}><StockRow stock={stock}/></div>)}</div></div></div> }
function AnalysisPanel({ kind, payload, name }) { const [status, setStatus] = useState('idle'); const [analysis, setAnalysis] = useState(''); const [error, setError] = useState(''); const ask = async () => { setStatus('loading'); setError(''); try { setAnalysis(await getAnalysis(kind, payload)); setStatus('ready'); } catch (requestError) { setError(requestError.message || 'Unable to load AI analysis.'); setStatus('error'); } }; return <section id={`ai-${kind}`} className="panel ai-analysis"><div className="ai-analysis-head"><div><div className="empty-mark"><Icon name="spark"/></div><small>STOXY AI · LIVE RESEARCH</small><h3>Get a focused read on {name}.</h3></div><button onClick={ask} className="button small" disabled={status==='loading'}>{status==='loading' ? 'Analysing…' : 'Ask Stoxy AI'} <Icon name="spark" size={14}/></button></div>{status==='idle' && <p>Generate a live thesis using the market context available for this instrument.</p>}{status==='error' && <p className="analysis-error">{error}</p>}{status==='ready' && <div className="analysis-copy">{analysis}</div>}</section> }
function StockDetail() { const stockPayload = { stockName: 'Reliance Industries', stockSymbol: 'RELIANCE', companyName: 'Reliance Industries Limited', exchange: 'NSE', instrumentKey: 'NSE_EQ|INE002A01018', isin: 'INE002A01018' }; const askAi = () => { document.getElementById('ai-stock')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); document.querySelector('#ai-stock .button')?.click(); }; return <div className="stock-detail"><div className="stock-hero"><div className="company-title"><StockLogo symbol="RELIANCE" tone="violet"/><div><h2>Reliance Industries</h2><span>RELIANCE · NSE</span></div></div><div className="detail-price"><strong>₹1,431.20</strong><em>+17.80 (1.26%) Today</em></div><button className="outline-button"><Icon name="plus" size={14}/> Watchlist</button><button onClick={askAi} className="ai-detail-button"><Icon name="spark" size={15}/> Ask Stoxy AI</button></div><div className="stock-tabs"><button className="active">Overview</button><button>Financials</button><button>News</button></div><div className="stock-chart-card panel"><div><small>PRICE PERFORMANCE · LIVE CHART</small><h3>On an upward path.</h3></div><div className="stock-chart"><LineChart/></div></div><div className="detail-grid"><div className="panel key-stats"><small>KEY STATISTICS</small>{[['Market cap','₹19.36L Cr'],['P/E ratio','28.41'],['52 week high','₹1,608.80'],['Dividend yield','0.39%']].map(([key,value])=><div key={key}><span>{key}</span><b>{value}</b></div>)}</div><AnalysisPanel kind="stock" payload={stockPayload} name="Reliance"/></div></div> }
function IndexDetail() { const indexPayload = { indexName: 'NIFTY 50', indexSymbol: 'NIFTY 50', exchange: 'NSE', segment: 'INDEX', instrumentKey: 'NSE_INDEX|Nifty 50' }; const askAi = () => { document.getElementById('ai-index')?.scrollIntoView({ behavior: 'smooth', block: 'center' }); document.querySelector('#ai-index .button')?.click(); }; return <div className="stock-detail index-detail"><div className="stock-hero"><div className="company-title"><div className="index-mark">50</div><div><h2>NIFTY 50</h2><span>NSE INDEX · 50 CONSTITUENTS</span></div></div><div className="detail-price"><strong>24,781.50</strong><em>+156.20 (0.64%) Today</em></div><button onClick={askAi} className="ai-detail-button"><Icon name="spark" size={15}/> Ask Stoxy AI</button></div><div className="stock-tabs"><button className="active">Overview</button><button>Constituents</button><button>Performance</button></div><div className="stock-chart-card panel"><div><small>INDEX PERFORMANCE · LIVE CHART</small><h3>Strong through the close.</h3></div><div className="stock-chart"><LineChart/></div></div><div className="detail-grid"><div className="panel key-stats"><small>INDEX METRICS</small>{[['Day high','24,812.65'],['Day low','24,625.40'],['52 week high','26,277.35'],['Constituents','50']].map(([key,value])=><div key={key}><span>{key}</span><b>{value}</b></div>)}</div><AnalysisPanel kind="index" payload={indexPayload} name="NIFTY 50"/></div></div> }
function SearchModal({ close, go }) { return <AnimatePresence><motion.div className="modal-backdrop" onMouseDown={close} initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }}><motion.div className="search-modal" onMouseDown={event=>event.stopPropagation()} initial={{ opacity: 0, y: -14, scale: .98 }} animate={{ opacity: 1, y: 0, scale: 1 }} transition={{ duration: .2 }}><div className="modal-search"><Icon name="search"/><input autoFocus placeholder="Search stocks, indices and ETFs"/><kbd>ESC</kbd><button onClick={close}><Icon name="close" size={17}/></button></div><div className="search-section"><small>TRENDING ON STOXY</small>{stocks.slice(0,3).map(stock=><button onClick={()=>{go('stock');close()}} className="search-result" key={stock.symbol}><StockLogo symbol={stock.symbol} tone={stock.tone}/><span><b>{stock.name}</b><em>{stock.symbol} · NSE</em></span><strong>{stock.price}</strong><i>{stock.change}</i></button>)}</div><div className="search-footer"><span><kbd>↑↓</kbd> to navigate</span><span><kbd>↵</kbd> to select</span></div></motion.div></motion.div></AnimatePresence> }
function Login({ go }) { return <div className="login-page"><button className="login-logo" onClick={()=>go('home')}><Logo/></button><div className="login-pane"><div className="login-form"><p className="eyebrow">WELCOME TO STOXY</p><h1>Invest with a<br/><i>clearer mind.</i></h1><p>Sign in to your personal market workspace.</p><button className="google-button"><span className="google-g">G</span> Continue with Google</button><div className="login-divider"><span>Secure sign in</span></div><p className="login-fine">By continuing, you agree to Stoxy’s <a>Terms of Use</a> and <a>Privacy Policy</a>.</p><button className="back-link" onClick={()=>go('home')}>← Back to home</button></div></div><div className="login-visual"><div className="login-orb"/><p className="eyebrow">YOUR MARKET, IN PERSPECTIVE</p><h2>Less noise.<br/>More <i>signal.</i></h2><div className="login-card"><small>MARKET SNAPSHOT</small><b>NIFTY 50 <em>+0.64%</em></b><strong>24,781.50</strong><LineChart mini/></div><p className="login-quote">“The quiet confidence to make your next move.”</p></div></div> }
function Footer() { return <footer><div className="footer-top"><div><Logo/><p>India’s more considered investing workspace.</p></div><div className="footer-links"><div><b>Product</b><a>Market overview</a><a>Watchlists</a><a>Portfolio</a><a>Stock screener</a></div><div><b>Company</b><a>About</a><a>Roadmap</a><a>Contact</a><a>Status</a></div><div><b>Legal</b><a>Privacy policy</a><a>Terms of use</a><a>Risk disclosure</a></div></div></div><div className="footer-bottom"><span>© 2026 Stoxy. Built for India.</span><span><a>GitHub</a><a>LinkedIn</a><a>𝕏</a></span></div></footer> }
export default App;
